#!/usr/bin/env python3
"""
Generate the A-Z coin index (wiki/markets/crypto/coin-index-a-z.md).

Statically wikilinks EVERY page in wiki/markets/crypto/ so coin pages are
reachable from the graph (Dataview listings do not create real links, so an
index of static links is required to un-orphan them). Re-run after bulk coin
imports; the file is fully regenerated each time.

Usage:
    .venv/Scripts/python.exe tools/build_coin_index.py
"""
import re
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CRYPTO = ROOT / "wiki" / "markets" / "crypto"
OUT = CRYPTO / "coin-index-a-z.md"

# Hub/meta pages that shouldn't be listed as coins
SKIP = {"coin-index-a-z", "crypto-overview", "crypto-markets"}


def parse_head(text):
    """Return (title, first_alias, type) from frontmatter."""
    m = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    title = alias = ptype = None
    if m:
        fm = m.group(1)
        tm = re.search(r'^title:\s*"?([^"\n]+?)"?\s*$', fm, re.M)
        if tm:
            title = tm.group(1).strip()
        am = re.search(r"^aliases:\s*\[([^\]]*)\]", fm, re.M)
        if am:
            first = re.findall(r'"([^"]+)"', am.group(1))
            alias = first[0] if first else None
        ym = re.search(r"^type:\s*(\S+)", fm, re.M)
        if ym:
            ptype = ym.group(1)
    return title, alias, ptype


def bucket(title):
    c = title[0].upper()
    return c if c.isalpha() else "0-9"


def main():
    entries = defaultdict(list)
    count = 0
    for f in sorted(CRYPTO.glob("*.md")):
        if f.stem in SKIP:
            continue
        title, alias, ptype = parse_head(f.read_text(encoding="utf-8", errors="ignore"))
        title = title or f.stem
        label = f"[[{f.stem}|{title}]]"
        if alias and alias.upper() != title.upper():
            label += f" ({alias})"
        if ptype == "redirect":
            label += " *(redirect)*"
        entries[bucket(title)].append((title.upper(), label))
        count += 1

    today = date.today().isoformat()
    lines = [
        "---",
        'title: "Crypto Coin Index (A–Z)"',
        "type: index",
        "created: 2026-07-19",
        f"updated: {today}",
        "status: good",
        "tags: [index, crypto, meta]",
        'related: ["[[crypto-overview]]", "[[crypto-markets]]", "[[markets-overview]]"]',
        "---",
        "",
        "# Crypto Coin Index (A–Z)",
        "",
        f"Alphabetical index of all **{count}** pages in `wiki/markets/crypto/` — every coin, "
        "token, and market page, statically linked so each is reachable from the graph. "
        "Regenerated by `tools/build_coin_index.py`; do not edit by hand.",
        "",
    ]
    for b in sorted(entries, key=lambda x: (x != "0-9", x)):
        lines.append(f"## {b}")
        lines.append("")
        for _, label in sorted(entries[b]):
            lines.append(f"- {label}")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} with {count} entries in {len(entries)} sections")


if __name__ == "__main__":
    main()
